roverlay-9999.ebuild: rovelay is no longer compatible with python2.7
Traceback (most recent call last):
  File "/usr/lib/python-exec/python2.7/roverlay", line 7, in <module>
    roverlay.defaultscript.main_installed()
  File "/usr/lib64/python2.7/site-packages/roverlay/defaultscript.py", line 35, in main_installed
    return main ( True, *args, **kw )
  File "/usr/lib64/python2.7/site-packages/roverlay/defaultscript.py", line 73, in main
    retcode = run_overlay_create ( main_env )
  File "/usr/lib64/python2.7/site-packages/roverlay/defaultscript.py", line 201, in run_overlay_create
    run_sync ( env )
  File "/usr/lib64/python2.7/site-packages/roverlay/defaultscript.py", line 177, in run_sync
    repo_list.load()
  File "/usr/lib64/python2.7/site-packages/roverlay/remote/repolist.py", line 128, in load
    self.load_file ( f )
  File "/usr/lib64/python2.7/site-packages/roverlay/remote/repolist.py", line 119, in load_file
    self.repos.extend ( new_repos )
  File "/usr/lib64/python2.7/site-packages/roverlay/remote/repoloader.py", line 82, in read_repofile
    **common_kwargs
  File "/usr/lib64/python2.7/site-packages/roverlay/remote/rsync.py", line 85, in __init__
    src_uri=src_uri, remote_uri=rsync_uri
  File "/usr/lib64/python2.7/site-packages/roverlay/remote/basicrepo.py", line 75, in __init__
    self._identifier = next ( self.__class__.ID_GENERATOR )
TypeError: IDGenerator object is not an iterator